### ISSUE TITLE
py3.8 安装依赖后提示 No module named 

### ISSUE THREAD

**Issue by thankU-ubi** [chingkingm/Hoshinobot-plugin-petpet#23]
[2022-05-17 19:02:59,764 nonebot] ERROR: Failed to import "hoshino.modules.petpet.data_source", error: No module named 'typing_extensions'
[2022-05-17 19:02:59,765 nonebot] ERROR: No module named 'typing_extensions'
Traceback (most recent call last):
  File "C:\Users\servers\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\servers\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\hoshinoBOT\HoshinoBot\hoshino\modules\petpet\__init__.py", line 10, in <module>
    from .data_source import commands, make_image
  File "D:\hoshinoBOT\HoshinoBot\hoshino\modules\petpet\data_source.py", line 5, in <module>
    from .utils import to_image
  File "D:\hoshinoBOT\HoshinoBot\hoshino\modules\petpet\utils.py", line 10, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'
[2022-05-17 19:02:59,770 nonebot] INFO: Succeeded to import "hoshino.modules.petpet.download"
[2022-05-17 19:02:59,775 nonebot] ERROR: Failed to import "hoshino.modules.petpet.functions", error: No module named 'typing_extensions'
[2022-05-17 19:02:59,777 nonebot] ERROR: No module named 'typing_extensions'
Traceback (most recent call last):
  File "C:\Users\servers\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\servers\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\hoshinoBOT\HoshinoBot\hoshino\modules\petpet\__init__.py", line 10, in <module>
    from .data_source import commands, make_image
  File "D:\hoshinoBOT\HoshinoBot\hoshino\modules\petpet\data_source.py", line 5, in <module>
    from .utils import to_image
  File "D:\hoshinoBOT\HoshinoBot\hoshino\modules\petpet\utils.py", line 10, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'
[2022-05-17 19:02:59,785 nonebot] ERROR: Failed to import "hoshino.modules.petpet.models", error: No module named 'typing_extensions'
[2022-05-17 19:02:59,785 nonebot] ERROR: No module named 'typing_extensions'
Traceback (most recent call last):
  File "C:\Users\servers\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\servers\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\hoshinoBOT\HoshinoBot\hoshino\modules\petpet\__init__.py", line 10, in <module>
    from .data_source import commands, make_image
  File "D:\hoshinoBOT\HoshinoBot\hoshino\modules\petpet\data_source.py", line 5, in <module>
    from .utils import to_image
  File "D:\hoshinoBOT\HoshinoBot\hoshino\modules\petpet\utils.py", line 10, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'
[2022-05-17 19:02:59,796 nonebot] ERROR: Failed to import "hoshino.modules.petpet.utils", error: No module named 'typing_extensions'
[2022-05-17 19:02:59,797 nonebot] ERROR: No module named 'typing_extensions'
Traceback (most recent call last):
  File "C:\Users\servers\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\servers\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\hoshinoBOT\HoshinoBot\hoshino\modules\petpet\__init__.py", line 10, in <module>
    from .data_source import commands, make_image
  File "D:\hoshinoBOT\HoshinoBot\hoshino\modules\petpet\data_source.py", line 5, in <module>
    from .utils import to_image
  File "D:\hoshinoBOT\HoshinoBot\hoshino\modules\petpet\utils.py", line 10, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'

**Comment by chingkingm** [comment]
`typing_extensions` 也需要装，requirements漏掉了，抱歉。
``` bash
pip install typing_extensions
```
