### ISSUE TITLE
安装遇到问题

### ISSUE THREAD

**Issue by RyanJiang184** [chingkingm/Hoshinobot-plugin-petpet#30]
[2022-12-05 16:45:03,306 nonebot] ERROR: Failed to import "hoshino.modules.Hoshinobot-plugin-petpet.utils", error: Bindings generation error. Submodule name should always start with a parent module name. Parent name: cv2.cv2. Submodule name: cv2
[2022-12-05 16:45:03,306 nonebot] ERROR: Bindings generation error. Submodule name should always start with a parent module name. Parent name: cv2.cv2. Submodule name: cv2
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\HoshinoBot\HoshinoBot\hoshino\modules\Hoshinobot-plugin-petpet\__init__.py", line 11, in <module>
    from .data_source import commands, make_image
  File "C:\Users\Administrator\Desktop\HoshinoBot\HoshinoBot\hoshino\modules\Hoshinobot-plugin-petpet\data_source.py", line 5, in <module>
    from .utils import to_image
  File "C:\Users\Administrator\Desktop\HoshinoBot\HoshinoBot\hoshino\modules\Hoshinobot-plugin-petpet\utils.py", line 4, in <module>
    from cv2 import cv2 as cv
ImportError: Bindings generation error. Submodule name should always start with a parent module name. Parent name: cv2.cv2. Submodule name: cv2

是按照正常的安装方法安装的，前面Issues的方法也试过了，但是还是报错了，遇到了这个问题。

**Comment by RyanJiang184** [comment]
已经解决了，我把utils.py中的
from cv2 import cv2 as cv
改成了
import cv2 as cv
然后问题就解决了
