### ISSUE TITLE
出错了，稍后再试了，没有反应

### ISSUE THREAD

**Issue by Guanchang3** [chingkingm/Hoshinobot-plugin-petpet#6]
![image](https://user-images.githubusercontent.com/48749711/157696256-01595176-c293-4b82-b6cb-be9ee3c6baad.png)

![image](https://user-images.githubusercontent.com/48749711/157696689-81e87be7-8967-4e24-bb67-8dead75c634c.png)

后台没有产生日志，挺难受的。。不知道怎么排查，求大佬相助

**Comment by chingkingm** [comment]
现版本报这个错误之前应该是有打印报错信息的，实在没有的话你可以注释掉__init.py__中最后一个except即86-88行。

**Comment by Guanchang3** [comment]
[2022-03-11 12:00:35,140 头像表情包] ERROR: <class 'ImportError'> occured when gen_image handling message 902044346.
[2022-03-11 12:00:35,144 头像表情包] ERROR: Using SOCKS proxy, but the 'socksio' package is not installed. Make sure to install httpx using `pip install httpx[socks]`.
Traceback (most recent call last):
  File "/root/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/root/HoshinoBot/hoshino/modules/Hoshinobot-plugin-petpet/__init__.py", line 81, in gen_image
    im = await make_image(com, sender, users, args=args)
  File "/root/HoshinoBot/hoshino/modules/Hoshinobot-plugin-petpet/data_source.py", line 57, in make_image
    await download_image(sender, command.convert)
  File "/root/HoshinoBot/hoshino/modules/Hoshinobot-plugin-petpet/data_source.py", line 46, in download_image
    img = await download_avatar(user.qq)
  File "/usr/local/lib/python3.8/site-packages/aiocache/decorators.py", line 93, in wrapper
    return await self.decorator(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/aiocache/decorators.py", line 108, in decorator
    result = await f(*args, **kwargs)
  File "/root/HoshinoBot/hoshino/modules/Hoshinobot-plugin-petpet/download.py", line 59, in download_avatar
    data = await download_url(url)
  File "/root/HoshinoBot/hoshino/modules/Hoshinobot-plugin-petpet/download.py", line 20, in download_url
    async with httpx.AsyncClient() as client:
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1384, in __init__
    self._mounts: typing.Dict[URLPattern, typing.Optional[AsyncBaseTransport]] = {
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1387, in <dictcomp>
    else self._init_proxy_transport(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1440, in _init_proxy_transport
    return AsyncHTTPTransport(
  File "/usr/local/lib/python3.8/site-packages/httpx/_transports/default.py", line 296, in __init__
    raise ImportError(
ImportError: Using SOCKS proxy, but the 'socksio' package is not installed. Make sure to install httpx using `pip install httpx[socks]`.

大概是我本地默认了走了代理然后缺少了py包

解决方法是执行下面三句（不确定是不是全都要，总之装了没问题）：
```
pip install httpx-socks
pip install httpx[socks]
pip install httpcore[socks]
```

装完后重启hoshino，正常运行

**Comment by chingkingm** [comment]
好的，我没遇到这个问题
